import assert from 'node:assert/strict';
import { test, before, after } from 'node:test';
import fs from 'node:fs';
const { PGlite } = await import(process.env.CASHFLOW_PGLITE_MODULE || '@electric-sql/pglite');
// PGlite serializes statements on one connection. Promise.all exercises concurrent
// callers, not independent PostgreSQL sessions. Verify cross-session locks in staging.
let db;
const actor='10000000-0000-4000-8000-000000000001', customer='20000000-0000-4000-8000-000000000001';
const movement = (overrides={}) => ({operation:'movement',id:null,kind:'funding_disbursement',basis:'actual',cash_date:'2020-01-02',amount:1234,installment_no:null,source_reference:'fixture-bank-reference',note:'',reason:'증빙 확인',...overrides});
const snapshot=async()=> (await db.query('select public.read_customer_cashflow($1,$2) as state',[actor,customer])).rows[0].state;
const save=async(change,key=crypto.randomUUID(),version=null,uid=actor)=>{const v=version??(await snapshot()).version;return (await db.query('select public.save_customer_cashflow($1,$2,$3,$4,$5::jsonb) as state',[uid,customer,key,v,JSON.stringify(change)])).rows[0].state;};
before(async()=>{
 db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create function auth.uid() returns uuid language sql as 'select null::uuid';
 create table public.admins(user_id uuid primary key);create table public.customers(id uuid primary key,first_payment_date date,rental_months integer,rental_price bigint,paid_count integer,receipt_ledger jsonb);
 create function public.is_admin(uuid) returns boolean language sql as 'select exists(select 1 from public.admins where user_id=$1)';
 insert into public.admins values('${actor}');insert into public.customers values('${customer}','2020-01-20',3,333,1,null);`);
 await db.exec(fs.readFileSync(new URL('../supabase/drafts/20261002_cashflow.sql',import.meta.url),'utf8'));
 // Fifteen synthetic historical rows, across four customers, are preservation fixtures.
 for(let n=1;n<=4;n++){const id=`40000000-0000-4000-8000-${String(n).padStart(12,'0')}`;await db.query('insert into public.customers(id) values($1);',[id]);await db.query("insert into public.cashflow_profiles(customer_id,funding_type) values($1,'own')",[id]);for(let k=0;k<(n===4?3:4);k++)await db.query("insert into public.cashflow_movements(customer_id,kind,basis,cash_date,amount,source_reference) values($1,'funding_disbursement','actual','2020-01-01',$2,$3)",[id,n*100+k,`fixture-old-${n}-${k}`]);}
 await db.exec('create table public.fixture_preserved as select * from public.cashflow_movements');
 await db.exec(fs.readFileSync(new URL('../supabase/drafts/20261002_cashflow_writes.sql',import.meta.url),'utf8'));
});
after(async()=>{await db.close();});
test('anon/authenticated cannot call RPC or write financial ledger',async()=>{for(const role of ['anon','authenticated']){await db.exec(`set role ${role}`);await assert.rejects(()=>snapshot(),/permission denied/);await assert.rejects(()=>db.query("insert into public.cashflow_movements(customer_id,kind,basis,source_reference) values($1,'funding_disbursement','actual','denied')",[customer]),/permission denied/);await db.exec('reset role');}});
test('service role RPC still rejects non-admin actor',async()=>{await db.exec('set role service_role');const version=(await snapshot()).version;await assert.rejects(()=>save(movement(),crypto.randomUUID(),version,'90000000-0000-4000-8000-000000000001'),/CASHFLOW_FORBIDDEN/);await db.exec('reset role');});
test('explicit schedule keeps one-won remainder, does not infer receipts',async()=>{const c={operation:'schedule',first_payment_date:'2020-01-20',rental_months:3,rental_price:333,expected_total:1000,payment_schedule:[{no:1,dueDate:'2020-01-20',amount:333},{no:2,dueDate:'2020-02-20',amount:333},{no:3,dueDate:'2020-03-21',amount:334}],reason:'일정 확인'};const s=await save(c);assert.equal(s.snapshot.customer.payment_schedule[2].amount,334);assert.equal(s.snapshot.customer.payment_schedule[2].dueDate,'2020-03-21');assert.equal(s.snapshot.customer.paid_count,1);assert.equal(s.snapshot.movements.length,0);await assert.rejects(()=>save({...c,expected_total:999}),/CASHFLOW_INVALID/);});
test('double-click, timeout retry and concurrent same request record exactly once',async()=>{const request=crypto.randomUUID(), version=(await snapshot()).version;const c=movement();const responses=await Promise.all([save(c,request,version),save(c,request,version)]);assert.equal(responses[0].snapshot.movements.length,1);assert.equal(responses[1].snapshot.movements.length,1);assert.equal((await snapshot()).snapshot.movements.length,1);assert.equal((await snapshot()).snapshot.profile.funding_type,null);await save(c,request,version);assert.equal((await snapshot()).snapshot.movements.length,1);await assert.rejects(()=>save({...c,amount:1235},request,version),/CASHFLOW_REQUEST_REUSED/);});
test('new request cannot duplicate same source or exact cash event',async()=>{await assert.rejects(()=>save(movement()),/CASHFLOW_DUPLICATE/);await assert.rejects(()=>save(movement({source_reference:'fixture-new-ref'})),/CASHFLOW_DUPLICATE/);});
test('concurrent different saves with stale snapshot conflict',async()=>{const version=(await snapshot()).version;const results=await Promise.allSettled([save(movement({source_reference:'fixture-concurrent-a',amount:2001}),crypto.randomUUID(),version),save(movement({source_reference:'fixture-concurrent-b',amount:2002}),crypto.randomUUID(),version)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.match(results.find(r=>r.status==='rejected').reason.message,/CASHFLOW_CONFLICT/);});
test('correction preserves movement ID/source and audits before/after',async()=>{const before=await snapshot(), row=before.snapshot.movements.find(m=>m.source_reference==='fixture-bank-reference');const key=crypto.randomUUID();await save(movement({id:row.id,amount:1300,reason:'입력 오류 정정'}),key);const after=await snapshot();const updated=after.snapshot.movements.find(m=>m.id===row.id);assert.equal(updated.source_reference,row.source_reference);assert.equal(updated.amount,1300);assert.equal(after.snapshot.movements.length,before.snapshot.movements.length);const audit=(await db.query('select * from public.cashflow_write_audit where request_id=$1',[key])).rows[0];assert.equal(audit.actor_id,actor);assert.equal(audit.before_state.movements.find(m=>m.id===row.id).amount,1234);assert.equal(audit.after_state.movements.find(m=>m.id===row.id).amount,1300);});
test('forced audit failure rolls back movement and newly-created profile',async()=>{const before=await snapshot();await db.exec("create function public.fixture_fail_audit() returns trigger language plpgsql as $$begin raise exception 'fixture failure';end$$;create trigger fixture_fail before insert on public.cashflow_write_audit for each row execute function public.fixture_fail_audit();");await assert.rejects(()=>save(movement({source_reference:'fixture-rollback',amount:3000})),/fixture failure/);assert.deepEqual(await snapshot(),before);await db.exec('drop trigger fixture_fail on public.cashflow_write_audit;drop function public.fixture_fail_audit();');});
test('forced movement failure rolls back an inserted profile',async()=>{// Use a new clean synthetic customer to verify profile rollback.
 const fresh='50000000-0000-4000-8000-000000000001';await db.query('insert into public.customers(id) values($1)',[fresh]);const v=(await db.query('select public.read_customer_cashflow($1,$2) as state',[actor,fresh])).rows[0].state.version;
 await db.exec("create function public.fixture_fail_movement() returns trigger language plpgsql as $$begin raise exception 'fixture movement failure';end$$;create trigger fixture_fail before insert on public.cashflow_movements for each row execute function public.fixture_fail_movement();");await assert.rejects(()=>db.query('select public.save_customer_cashflow($1,$2,$3,$4,$5::jsonb)',[actor,fresh,crypto.randomUUID(),v,JSON.stringify(movement({source_reference:'fixture-rollback-profile'}))]),/fixture movement failure/);assert.equal((await db.query('select * from public.cashflow_profiles where customer_id=$1',[fresh])).rows.length,0);await db.exec('drop trigger fixture_fail on public.cashflow_movements;drop function public.fixture_fail_movement();');});
test('legacy receipt ledger blocks mixed-source writes',async()=>{await db.query("update public.customers set receipt_ledger='{}' where id=$1",[customer]);await assert.rejects(()=>save(movement({kind:'rental_receipt',installment_no:1,source_reference:'fixture-receipt'})),/CASHFLOW_LEGACY_LEDGER/);await db.query('update public.customers set receipt_ledger=null where id=$1',[customer]);});
test('partial actual receipts do not increase legacy paid_count',async()=>{const s=await save(movement({kind:'rental_receipt',installment_no:2,amount:111,source_reference:'fixture-receipt'}));assert.equal(s.snapshot.customer.paid_count,1);assert.equal(s.snapshot.movements.filter(m=>m.kind==='rental_receipt').length,1);});
test('invalid/future actual, installment, unsafe money and profile conflicts rollback',async()=>{const before=await snapshot();for(const patch of [{cash_date:'2199-01-01'},{cash_date:'2020-02-30'},{amount:1.5},{amount:-1},{amount:9007199254740992},{kind:'rental_receipt',installment_no:4},{kind:'rental_receipt',installment_no:1,basis:'planned'}])await assert.rejects(()=>save(movement(patch)),/CASHFLOW_INVALID/);assert.deepEqual(await snapshot(),before);});
test('all fifteen historical IDs, dates, amounts and source references remain byte-for-byte intact',async()=>{assert.equal((await db.query('select count(*) n from public.fixture_preserved')).rows[0].n,15);const rows=await db.query('select id from public.fixture_preserved p where not exists(select 1 from public.cashflow_movements m where to_jsonb(m)=to_jsonb(p))');assert.deepEqual(rows.rows,[]);});
test('existing source reference stays exact, even if short or padded',async()=>{const row=(await db.query("insert into public.cashflow_movements(customer_id,kind,basis,cash_date,amount,source_reference) values($1,'funding_disbursement','actual','2020-02-02',77,' x ') returning *",[customer])).rows[0];await save(movement({id:row.id,source_reference:' x ',cash_date:'2020-02-02',amount:78}));const current=(await snapshot()).snapshot.movements.find(m=>m.id===row.id);assert.equal(current.source_reference,' x ');assert.equal(current.amount,78);});
test('legacy allocation blocks schedule shrink before anything changes',async()=>{await db.query("update public.customers set receipt_ledger=$2::jsonb where id=$1",[customer,JSON.stringify({legacyPaidCount:0,entries:[{id:'legacy',no:3,amount:1,receivedDate:'2020-01-01'}]})]);const before=await snapshot();await assert.rejects(()=>save({operation:'schedule',first_payment_date:'2020-01-20',rental_months:1,rental_price:100,expected_total:100,payment_schedule:[{no:1,dueDate:'2020-01-20',amount:100}],reason:'일정 변경'}),/CASHFLOW_LEGACY_LEDGER/);assert.deepEqual(await snapshot(),before);await db.query('update public.customers set receipt_ledger=null where id=$1',[customer]);});
test('own funding cannot conceal creditor transactions',async()=>{await save({operation:'profile',funding_type:'own',creditor_name:null,reason:'자금 확인'});await assert.rejects(()=>save(movement({kind:'creditor_payment',amount:99,source_reference:'fixture-creditor'})),/CASHFLOW_PROFILE_CONFLICT/);await save({operation:'profile',funding_type:'securitized',creditor_name:'가상 채권사',reason:'분류 확인'});await save(movement({kind:'creditor_payment',amount:99,source_reference:'fixture-creditor'}));await assert.rejects(()=>save({operation:'profile',funding_type:'own',creditor_name:null,reason:'분류 변경'}),/CASHFLOW_PROFILE_CONFLICT/);});
test('audit failure rolls back schedule and profile updates too',async()=>{const before=await snapshot();await db.exec("create function public.fixture_fail_audit() returns trigger language plpgsql as $$begin raise exception 'fixture failure';end$$;create trigger fixture_fail before insert on public.cashflow_write_audit for each row execute function public.fixture_fail_audit();");await assert.rejects(()=>save({operation:'profile',funding_type:null,creditor_name:null,reason:'분류 변경'}),/fixture failure/);await assert.rejects(()=>save({operation:'schedule',first_payment_date:'2020-01-21',rental_months:3,rental_price:10,expected_total:30,payment_schedule:[{no:1,dueDate:'2020-01-21',amount:10},{no:2,dueDate:'2020-02-21',amount:10},{no:3,dueDate:'2020-03-21',amount:10}],reason:'일정 정정'}),/fixture failure/);assert.deepEqual(await snapshot(),before);await db.exec('drop trigger fixture_fail on public.cashflow_write_audit;drop function public.fixture_fail_audit();');});
test('cross-customer same-reference submissions yield one event and conclusive duplicate',async()=>{
 const other='50000000-0000-4000-8000-000000000002';await db.query('insert into public.customers(id) values($1)',[other]);
 const otherVersion=(await db.query('select public.read_customer_cashflow($1,$2) as state',[actor,other])).rows[0].state.version;
 const currentVersion=(await snapshot()).version;
 const c=movement({source_reference:'fixture-cross-customer',amount:5432});
 const responses=await Promise.allSettled([save(c,crypto.randomUUID(),currentVersion),db.query('select public.save_customer_cashflow($1,$2,$3,$4,$5::jsonb)',[actor,other,crypto.randomUUID(),otherVersion,JSON.stringify(c)])]);
 assert.equal(responses.filter(r=>r.status==='fulfilled').length,1);assert.match(responses.find(r=>r.status==='rejected').reason.message,/CASHFLOW_DUPLICATE/);
 assert.equal((await db.query("select count(*) n from public.cashflow_movements where source_reference='fixture-cross-customer'")).rows[0].n,1);
});
test('known unique violations are definitive rollback errors, not unknown outcomes',async()=>{
 const before=await snapshot();
 await db.exec("create function public.fixture_unique_error() returns trigger language plpgsql as $$begin raise unique_violation using constraint='cashflow_movements_source_reference_key';end$$;create trigger fixture_fail before insert on public.cashflow_movements for each row execute function public.fixture_unique_error();");
 await assert.rejects(()=>save(movement({source_reference:'fixture-maintenance-race',amount:9876})),/CASHFLOW_DUPLICATE/);
 assert.deepEqual(await snapshot(),before);await db.exec('drop trigger fixture_fail on public.cashflow_movements;drop function public.fixture_unique_error();');
});
