import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import { execFileSync } from 'node:child_process';
import test from 'node:test';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { loadSource } from './cashflow-loader.mjs';
const d=JSON.parse(fs.readFileSync('design-system/tokens.json','utf8'));
const flat={};
function flatten(o,path='') { if(o&&typeof o==='object'&&'$value'in o) flat[path]=o; else if(o&&typeof o==='object') for(const [k,v] of Object.entries(o)) flatten(v,path?`${path}.${k}`:k); }
flatten(d);
const resolve=key=>{ const value=flat[key].$value; const match=String(value).match(/^\{(.+)\}$/);return match?resolve(match[1]):value; };
const variable=key=>'--ph-'+key.replace(/([a-z])([A-Z])/g,'$1-$2').toLowerCase().replaceAll('.','-');
const css=fs.readFileSync('design-system/components.css','utf8');
const nav={'next/navigation':{useRouter:()=>({push(){},refresh(){}}),usePathname:()=>'/ph-console-8f27x/customers',useSearchParams:()=>new URLSearchParams()}};
const html=(Component,props={})=>renderToStaticMarkup(React.createElement(Component,props));
function luminance(hex){return hex.slice(1).match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4).reduce((s,x,i)=>s+x*[.2126,.7152,.0722][i],0);}
function contrast(a,b){const x=luminance(a),y=luminance(b);return(Math.max(x,y)+.05)/(Math.min(x,y)+.05);}
test('generated CSS is fresh and aliases have unique names, valid types, and no missing/cyclic references',()=>{assert.match(execFileSync('python',['design-system/generate_css.py','--check'],{encoding:'utf8'}),/Validated fresh CSS/);});
test('every web component token is consumed by CSS or the chart, with media tokens scoped separately',()=>{const source=css+fs.readFileSync('src/components/admin/CashflowCharts.tsx','utf8');for(const key of Object.keys(flat).filter(k=>k.startsWith('component.')&&!/^component\.(document|slide|card)\./.test(k)))assert.ok(source.includes(variable(key)),key);});
test('interactive component colors reference semantic roles, not raw text roles as fills',()=>{for(const [key,value]of Object.entries(flat).filter(([k,v])=>k.startsWith('component.')&&v.$type==='color')){assert.match(value.$value,/^\{semantic\./,key);if(/(?:\.fill|Fill)$/.test(key))assert.ok(!value.$value.includes('.text.'),key);}});
test('normal, hover, pressed, status and inverse navigation text meet AA contrast',()=>{for(const variant of ['primary','secondary','danger','ghost'])for(const fill of ['fill','hoverFill','pressedFill'])assert.ok(contrast(resolve(`component.button.${variant}.text`),resolve(`component.button.${variant}.${fill}`))>=4.5,`${variant}.${fill}`);for(const status of ['neutral','success','warning','danger'])assert.ok(contrast(resolve(`component.status.${status}.text`),resolve(`component.status.${status}.fill`))>=4.5,status);for(const text of ['text','label','activeText'])assert.ok(contrast(resolve(`component.sidebar.${text}`),resolve('component.sidebar.fill'))>=4.5,text);assert.ok(contrast(resolve('component.input.border'),resolve('component.input.fill'))>=3);});
test('button variants use the component classes and loading prevents duplicate activation',()=>{const {Button}=loadSource('src/components/Button.tsx');for(const variant of ['primary','secondary','danger','ghost'])assert.match(html(Button,{variant,context:'workspace',children:'가상 버튼'}),new RegExp(`ph-button--${variant}`));const rendered=html(Button,{loading:true,children:'저장 중…'});assert.match(rendered,/disabled=""/);assert.match(rendered,/aria-busy="true"/);});
test('field connects label, hint and error; readonly/disabled are native and zero is preserved',()=>{const {Field}=loadSource('src/components/ui/Field.tsx');const rendered=html(Field,{id:'test-amount',label:'금액 (원)',defaultValue:'0',hint:'원 단위',error:'확인 필요',readOnly:true});assert.match(rendered,/for="test-amount"/);assert.match(rendered,/aria-describedby="test-amount-hint test-amount-error"/);assert.match(rendered,/aria-invalid="true"/);assert.match(rendered,/readOnly=""/);assert.match(rendered,/value="0"/);assert.match(html(Field,{id:'disabled',label:'비활성',disabled:true}),/disabled=""/);});
test('customer list retains long Korean, original units, zero and missing values, with real detail links and scroll region',()=>{const {CustomerTable}=loadSource('src/components/admin/CustomerTable.tsx',nav);const rendered=html(CustomerTable,{customers:[{id:'fictional',hospital_name:'가상 긴한글병원 동부지점',phone:'010-0000-0000',needed_funds:'0원',intake_date:'2026-10-03',stage:'screening_3'}],agentName:new Map()});for(const value of ['가상 긴한글병원 동부지점','010-0000-0000','0원','2026-10-03','3차 안내(스크리닝)'])assert.ok(rendered.includes(value),value);assert.match(rendered,/role="region"/);assert.match(rendered,/tabindex="0"/);assert.match(rendered,/scope="col"/);assert.match(rendered,/href="\/ph-console-8f27x\/customers\/fictional"/);assert.match(rendered,/ph-date/);assert.match(html(CustomerTable,{customers:[],agentName:new Map()}),/해당 단계의 고객이 없습니다/);assert.ok(!html(CustomerTable,{customers:[],agentName:new Map(),failed:true}).includes('해당 단계의 고객이 없습니다'));});
test('row pointer navigation does not override links or text selection',()=>{const calls=[];const {ClickableRow}=loadSource('src/components/admin/ClickableRow.tsx',{'next/navigation':{useRouter:()=>({push:href=>calls.push(href)})}});const row=ClickableRow({href:'/fictional',children:null});const old=global.window;try{global.window={getSelection:()=>({toString:()=>''})};row.props.onClick({target:{closest:()=>true}});assert.equal(calls.length,0);global.window.getSelection=()=>({toString:()=>'selected text'});row.props.onClick({target:{closest:()=>false}});assert.equal(calls.length,0);global.window.getSelection=()=>({toString:()=>''});row.props.onClick({target:{closest:()=>false}});assert.deepEqual(calls,['/fictional']);}finally{global.window=old;}});
test('sidebar active state and empty counts have text labels and a current page marker',()=>{const {Sidebar}=loadSource('src/components/admin/Sidebar.tsx',nav);const rendered=html(Sidebar,{counts:{__all__:0},showCashflow:false});assert.equal((rendered.match(/aria-current="page"/g)||[]).length,1);assert.match(rendered,/ph-sidebar-label/);assert.match(rendered,/ph-sidebar-count">0/);assert.ok(!rendered.includes('월별 현금흐름'));});
test('mobile drawer uses a closed native dialog, a close control and a labelled trigger',()=>{const {AdminShell}=loadSource('src/components/admin/AdminShell.tsx',{...nav,'@/app/ph-console-8f27x/login/actions':{signOut:undefined}});const rendered=html(AdminShell,{counts:{},children:'가상 내용'});assert.match(rendered,/<dialog[^>]+id="admin-navigation"/);assert.ok(!/<dialog[^>]+\sopen/.test(rendered));assert.match(rendered,/aria-controls="admin-navigation"/);assert.match(rendered,/aria-expanded="false"/);assert.match(rendered,/>닫기<\/button>/);});
test('feedback distinguishes neutral empty, partial warning and persistent errors without color-only meaning',()=>{const {Feedback,EmptyState}=loadSource('src/components/ui/Feedback.tsx');assert.match(html(Feedback,{tone:'warning',title:'확인 필요',children:'확인분 0원'}),/role="status"/);assert.match(html(Feedback,{tone:'danger',urgent:true,children:'다시 시도해 주세요'}),/role="alert"/);assert.match(html(EmptyState,{title:'조회 결과 없음'}),/조회 결과 없음/);});
test('table density, no-fragment date and reduced-motion rules are wired',()=>{assert.match(css,/height:var\(--ph-component-data-table-row-height\)/);assert.match(css,/height:var\(--ph-component-data-table-compact-row-height\)/);assert.match(css,/padding:var\(--ph-component-data-table-cell-padding\)/);assert.match(css,/\.ph-date, \.ph-nowrap \{ white-space:nowrap/);assert.match(css,/prefers-reduced-motion:reduce/);});
test('business calculations, auth, mutations and retention sources are byte-identical to the baseline',()=>{const manifest=JSON.parse(fs.readFileSync('design-system/business-invariants.json','utf8'));for(const [file,hash]of Object.entries(manifest)){assert.equal(crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),hash,file);}});
test('contact server failure keeps entered values and exposes a persistent error; pending is a disabled button state',async()=>{
 const values={company:'가상 한글 회사',name:'가상 담당자',phone:'010-0000-0000',amount:'0원'};
 const state=['idle',''];let cursor=0,resets=0,complete;
 const {ContactForm}=loadSource('src/components/ContactForm.tsx',{react:{useState:()=>{const i=cursor++;return[state[i],v=>{state[i]=v}];}}});
 const render=()=>{cursor=0;return ContactForm();};
 const oldForm=global.FormData,oldFetch=global.fetch;
 try {global.FormData=class{entries(){return Object.entries(values)}};global.fetch=()=>new Promise(resolve=>{complete=resolve});const task=render().props.onSubmit({preventDefault(){},currentTarget:{reset(){resets++}}});assert.equal(state[0],'loading');assert.equal(render().props['aria-busy'],true);complete({ok:false,json:async()=>({error:'서버 저장 실패'})});await task;assert.equal(state[0],'error');assert.equal(state[1],'서버 저장 실패');assert.equal(resets,0);assert.equal(values.amount,'0원');assert.equal(values.company,'가상 한글 회사');}finally{global.FormData=oldForm;global.fetch=oldFetch;}
});

test('customer list query and filtering remain unchanged',()=>{const source=fs.readFileSync('src/app/ph-console-8f27x/(app)/customers/page.tsx','utf8');const start=source.indexOf('  const { stage }');const end=source.indexOf('  return (',start);assert.ok(start>=0&&end>start);assert.equal(crypto.createHash('sha256').update(source.slice(start,end)).digest('hex'),'d781c3b849286914ac5400310863903223beb181c38b1fbd13154abc9e828fbf');});

test('contact endpoint, payload and success/error flow remain unchanged',()=>{const source=fs.readFileSync('src/components/ContactForm.tsx','utf8');const start=source.indexOf('  async function handleSubmit');const end=source.indexOf('  if (status === "success")',start);assert.ok(start>=0&&end>start);assert.equal(crypto.createHash('sha256').update(source.slice(start,end)).digest('hex'),'e7e31ebd350ae4e9bcb72f477f4265121ccb725f25fece6ec29028e11bda3ebc');});

test('autosave timing and mutation calls remain unchanged',()=>{const source=fs.readFileSync('src/components/admin/AutosaveForm.tsx','utf8');const start=source.indexOf('  const [status');const end=source.indexOf('  return (',start);assert.ok(start>=0&&end>start);assert.equal(crypto.createHash('sha256').update(source.slice(start,end)).digest('hex'),'db750e528f8836d03aec74db885927116ccbead89240b398263d52dfd7af4b31');});

test('unreleased preview and editors are excluded from the production route tree',()=>{assert.ok(!fs.existsSync('src/app/design-preview'));assert.ok(!fs.existsSync('src/components/admin/CashflowEditor.tsx'));assert.ok(!fs.existsSync('src/components/admin/ContractPreparationEditor.tsx'));assert.ok(!fs.readFileSync('src/components/admin/Sidebar.tsx','utf8').includes('contract-preparations'));assert.ok(!fs.readFileSync('src/app/layout.tsx','utf8').includes('write-pause'));});
