import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {createRequire} from 'node:module';
import postcss from 'postcss';
import tailwind from '@tailwindcss/postcss';
const require=createRequire(import.meta.url);const{webpack}=require('next/dist/compiled/webpack/webpack');
const root=process.cwd(),base=path.join(root,'design-preview'),out=path.join(root,'design-preview-dist');
if(process.env.VERCEL_ENV==='production')throw Error('Preview-only build: production target rejected');
const manifest=JSON.parse(fs.readFileSync(path.join(base,'source-manifest.json'),'utf8'));
for(const[file,metadata]of Object.entries(manifest.exact_presentation_files)){if(crypto.createHash('sha256').update(fs.readFileSync(path.join(base,file))).digest('hex')!==metadata.sha256)throw Error('Presentation source drift: '+file);}
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out,{recursive:true});
const css=(await postcss([tailwind()]).process(fs.readFileSync(path.join(base,'styles/app.css'),'utf8'),{from:path.join(base,'styles/app.css')})).css;fs.writeFileSync(path.join(out,'design.css'),css);
const stats=await new Promise((resolve,reject)=>webpack({mode:'production',target:'web',entry:path.join(base,'entry.tsx'),devtool:false,output:{path:out,filename:'design.js'},resolve:{extensions:['.tsx','.ts','.js','.mjs'],alias:{'next/link$':path.join(base,'ui/Link.tsx'),'@/lib/cn$':path.join(base,'ui/cn.ts')}},module:{rules:[{test:/\.tsx?$/,exclude:/node_modules/,use:path.join(base,'transpile-loader.cjs')}]},optimization:{minimize:false}},(error,stats)=>error?reject(error):resolve(stats)));
if(stats.hasErrors())throw Error(stats.toString({all:false,errors:true,errorDetails:true}));
const modules=[...stats.compilation.modules].map(m=>m.resource).filter(Boolean);
const appModules=modules.filter(file=>!file.includes('node_modules'));
const allowed=new Set(['entry.tsx','ui/Button.tsx','ui/Field.tsx','ui/Feedback.tsx','ui/Link.tsx','ui/cn.ts'].map(f=>path.join(base,f)));
const forbidden=appModules.filter(file=>!allowed.has(file));if(forbidden.length)throw Error('Module outside pure UI allowlist: '+forbidden.join(', '));
const bundle=fs.readFileSync(path.join(out,'design.js'),'utf8');
for(const text of ['supabase','/api/contact','ph-console-','SUPABASE','resolvePaymentSchedule','projectCashflow','__next_internal_action_entry_do_not_use__'])if(bundle.includes(text))throw Error('Excluded business/backend/contact signature: '+text);
const emails=bundle.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)||[];
if(emails.some(value=>value!=='preview@example.com'))throw Error('Non-fictional email in preview');
const phones=bundle.match(/\b\d{2,4}-\d{3,4}(?:-\d{4})?\b/g)||[];
if(phones.some(value=>value!=='000-0000-0000'))throw Error('Non-fictional phone in preview');
for(const name of ['logo-mark.png','logo-mark-white.png'])fs.copyFileSync(path.join(root,'public',name),path.join(out,name));
fs.copyFileSync(path.join(base,'fixture-document.pdf'),path.join(out,'fixture-document.pdf'));
fs.writeFileSync(path.join(out,'index.html'),'<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>풍현 디자인 검토 v1.1</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css"><link rel="stylesheet" href="/design.css"></head><body class="ph-scope"><div id="root"></div><script src="/design.js" defer></script></body></html>');
fs.writeFileSync(path.join(out,'robots.txt'),'User-agent: *\nDisallow: /\n');
const audit={source_commit:manifest.source_commit,exact_presentation_files:7,app_modules:appModules.map(f=>path.relative(base,f)),backend_modules:0,business_logic_modules:0,real_contact_fields:0,server_functions:0,bundle_sha256:crypto.createHash('sha256').update(bundle).digest('hex'),static_files:fs.readdirSync(out)};
fs.writeFileSync(path.join(base,'build-audit.json'),JSON.stringify(audit,null,2)+'\n');console.log(JSON.stringify(audit,null,2));process.exit(0);
