import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Button,ButtonLink} from './ui/Button';
import {Field} from './ui/Field';
import {EmptyState,Feedback,StatusBadge} from './ui/Feedback';
const examples=[
 {name:'가상 한글이름이긴 사업장 동부지점',representative:'가상 담당자',phone:'000-0000-0000',amount:125000000,date:'2026-10-03',status:'확인 필요'},
 {name:'가상 0원 입력 예시',representative:'예시 담당자',phone:'000-0000-0000',amount:0,date:'2026-10-04',status:'0원 입력'},
 {name:'가상 미입력 예시',representative:'미입력',phone:'미입력',amount:null,date:'미입력',status:'미입력'},
];
const chart=[{label:'가상 항목 A',amount:125000000,height:130,color:'var(--ph-component-chart-rental)'},{label:'가상 항목 B',amount:0,height:2,color:'var(--ph-component-chart-inflow)'},{label:'가상 항목 C',amount:null,height:0,color:'var(--ph-component-chart-funding)'}];
const money=(value:number|null)=>value===null?'미입력':new Intl.NumberFormat('ko-KR').format(value)+'원';
const nav=[['overview','화면 개요'],['table','표 · 숫자'],['inputs','입력 · 버튼'],['chart','차트 예시'],['documents','문서 예시']] as const;
function Menu({close=()=>{}}:{close?:()=>void}) {return <nav aria-label="검토 메뉴" className="ph-sidebar flex flex-col gap-1 p-4"><p className="ph-sidebar-label">디자인 검토</p>{nav.map(([id,label])=><a key={id} href={'#'+id} onClick={close}>{label}</a>)}</nav>;}
function PreviewShell({children}:{children:React.ReactNode}) {
 const[open,setOpen]=useState(false);const drawer=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const dialog=drawer.current;if(!dialog)return;if(open&&!dialog.open)dialog.showModal();if(!open&&dialog.open)dialog.close();const desktop=window.matchMedia('(min-width: 1024px)');const close=()=>{if(desktop.matches){dialog.close();setOpen(false);}};desktop.addEventListener('change',close);return()=>desktop.removeEventListener('change',close);},[open]);
 return <div className="ph-scope ph-admin min-h-dvh bg-navy-50 lg:grid lg:grid-cols-[16rem_1fr]"><a href="#preview-main" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:bg-white focus:p-3">본문으로 이동</a><aside className="hidden bg-navy-900 lg:flex lg:flex-col"><div className="flex h-16 items-center gap-2 border-b border-navy-800 px-5"><img src="/logo-mark-white.png" alt="풍현 로고" width="32" height="32"/><span className="font-bold text-white">풍현 디자인 검토</span></div><Menu/></aside>
 <dialog ref={drawer} id="preview-navigation" aria-label="검토 메뉴" onClose={()=>setOpen(false)} onCancel={()=>setOpen(false)} onClick={event=>{if(event.target===event.currentTarget)setOpen(false);}} className="fixed inset-0 m-0 h-dvh max-h-none w-full max-w-none border-0 bg-transparent p-0 backdrop:bg-black/50"><aside className="ph-sidebar flex h-full w-72 max-w-[85vw] flex-col"><div className="flex min-h-16 items-center gap-2 border-b border-navy-700 px-5"><img src="/logo-mark-white.png" alt="풍현 로고" width="32" height="32"/><span className="font-bold text-white">풍현 디자인 검토</span><button type="button" onClick={()=>setOpen(false)} className="ml-auto min-h-11 px-2 text-sm text-white" autoFocus>닫기</button></div><div className="flex-1 overflow-y-auto"><Menu close={()=>setOpen(false)}/></div></aside></dialog>
 <div className="flex min-h-dvh min-w-0 flex-col"><header className="flex h-16 items-center justify-between border-b border-navy-200 bg-white px-4 sm:px-6"><button type="button" onClick={()=>setOpen(true)} aria-label="메뉴 열기" aria-expanded={open} aria-controls="preview-navigation" className="grid h-11 w-11 place-items-center rounded-lg text-navy-700 hover:bg-navy-50 lg:hidden">☰</button><span className="ml-auto text-sm text-navy-500">preview@example.com</span></header><main id="preview-main" tabIndex={-1} className="flex-1 p-4 sm:p-6 lg:p-8">{children}</main></div></div>;
}
function Gallery(){const[error,setError]=useState(false);const[tip,setTip]=useState<number|null>(null);return <PreviewShell><div className="space-y-8"><section id="overview"><p className="text-sm text-navy-500">가상자료 전용 · v1.1</p><h1 className="mt-2 text-2xl font-bold">풍현 컴포넌트와 상태</h1><p className="mt-2 text-sm text-navy-500">실제 고객·연락처·계산·업무 흐름을 포함하지 않습니다. 입력값은 전송하거나 저장하지 않습니다.</p></section>
 <section id="table"><h2 className="mb-3 text-lg font-semibold">표 · 숫자 · 긴 한글</h2><div className="ph-surface overflow-hidden"><p id="table-help" className="border-b border-navy-100 px-4 py-3 text-sm text-navy-500">가상 예시 3건 · 좁은 화면에서는 표를 좌우로 이동하세요.</p><div className="ph-table-scroll" tabIndex={0} role="region" aria-label="가상 예시 표" aria-describedby="table-help"><table className="ph-table min-w-[950px]"><caption className="sr-only">가상 표 · 모든 금액은 명시된 예시 값</caption><thead><tr>{['예시 이름','담당자','가상 연락처','예시 금액 (원)','예시 날짜','표시 상태'].map(t=><th key={t} scope="col">{t}</th>)}</tr></thead><tbody>{examples.map(row=><tr key={row.name}><td className="min-w-44 max-w-64 font-medium">{row.name}</td><td className="ph-nowrap">{row.representative}</td><td className="ph-nowrap">{row.phone}</td><td className="ph-number">{money(row.amount)}</td><td className="ph-date">{row.date}</td><td><StatusBadge>{row.status}</StatusBadge></td></tr>)}</tbody></table></div></div></section>
 <section id="inputs" className="ph-surface ph-surface--padded space-y-4"><h2 className="font-semibold">버튼 · 입력 상태</h2><div className="flex flex-wrap gap-3"><Button context="workspace">기본 버튼</Button><Button context="workspace" variant="secondary">보조 버튼</Button><Button context="workspace" variant="ghost">텍스트 버튼</Button><Button context="workspace" variant="danger">제거 예시</Button><Button context="workspace" disabled>사용 불가</Button><Button context="workspace" loading>저장 중…</Button></div><div className="grid gap-6 md:grid-cols-2"><Field id="example-name" label="가상 사업장명" hint="한글 입력과 붙여넣기를 확인하세요" placeholder="가상 사업장"/><Field id="example-money" label="예시 금액 (원)" defaultValue="0" inputMode="numeric" hint="0과 미입력은 구분합니다"/><Field id="example-invalid" label="예시 날짜" type="date" error="날짜를 입력해 주세요"/><Field id="example-readonly" label="읽기 전용" defaultValue="가상 값 유지" readOnly/><Field id="example-disabled" label="입력 불가" defaultValue="상태 예시" disabled/></div></section>
 <section className="ph-surface ph-surface--padded space-y-4"><h2 className="font-semibold">상태 · 피드백</h2><div className="flex flex-wrap gap-3"><StatusBadge>대기</StatusBadge><StatusBadge tone="success">표시 완료</StatusBadge><StatusBadge tone="warning">확인 필요</StatusBadge><StatusBadge tone="danger">실패 예시</StatusBadge></div><Feedback tone="warning" title="가상 부분 데이터">0원 예시 1건 · 미입력 예시 1건</Feedback><Button context="workspace" variant="secondary" onClick={()=>setError(v=>!v)}>실패 상태 {error?'닫기':'보기'}</Button>{error&&<Feedback tone="danger" urgent title="오류 표시 예시">입력한 내용은 그대로 남아 있습니다. 이 버튼은 실제 저장을 시도하지 않습니다.</Feedback>}<EmptyState title="가상 조회 결과가 없습니다">빈 상태를 확인하기 위한 예시입니다.</EmptyState></section>
 <section id="chart" className="ph-chart ph-surface ph-surface--padded"><h2 className="font-semibold">명시적 가상 숫자 차트</h2><p className="mt-2 text-sm text-navy-500">실제 계산 없이 정한 예시 값입니다. 막대를 클릭하거나 Tab으로 선택하면 전체 금액을 표시합니다.</p><div className="mt-6 flex items-end gap-4" style={{height:180}}>{chart.map((row,index)=><button type="button" key={row.label} className="flex min-h-11 min-w-20 flex-1 flex-col items-center justify-end gap-2" onMouseEnter={()=>setTip(index)} onFocus={()=>setTip(index)} onClick={()=>setTip(index)} onKeyDown={event=>{if(event.key==='Escape')setTip(null);}} aria-label={`${row.label} ${money(row.amount)}`} aria-describedby="chart-value"><span aria-hidden="true" style={{display:'block',height:row.height,width:36,background:row.color}}/><span>{row.label}</span></button>)}</div><div id="chart-value" role="status" aria-live="polite" className="mt-4 rounded-lg bg-navy-50 p-3">{tip===null?'막대를 선택하세요':`${chart[tip].label} · ${money(chart[tip].amount)}`}</div><details className="mt-4"><summary>표로 보기</summary><table className="ph-table ph-table--compact"><thead><tr><th scope="col">항목</th><th scope="col" className="ph-number">예시 금액 (원)</th></tr></thead><tbody>{chart.map(row=><tr key={row.label}><th scope="row">{row.label}</th><td className="ph-number">{money(row.amount)}</td></tr>)}</tbody></table></details></section>
 <section id="documents" className="ph-surface ph-surface--padded"><h2 className="font-semibold">가상 문서 예시</h2><p className="mt-2 text-sm">직접 생성한 1쪽 검토용 표본입니다. 실제 계약서나 고객자료가 아닙니다.</p><div className="mt-3 flex flex-wrap gap-3"><a className="ph-attachment-action" href="/fixture-document.pdf" target="_blank" rel="noopener noreferrer">가상 문서 보기 · 새 창</a><a className="ph-attachment-action" href="/fixture-document.pdf" download="fictional-design-specimen.pdf">가상 문서 다운로드</a></div></section></div></PreviewShell>;}
function PublicSample(){return <><header className="border-b border-navy-100 bg-white"><div className="mx-auto flex h-16 max-w-6xl items-center gap-2 px-6"><img src="/logo-mark.png" alt="풍현 로고" width="32" height="32"/><strong>풍현</strong><span className="ml-auto text-sm text-navy-500">공개 화면 디자인 예시</span></div></header><main><section className="bg-navy-900 px-6 py-24 text-white"><div className="mx-auto max-w-3xl text-center"><p className="text-sm text-navy-200">검토용 가상 화면</p><h1 className="mt-6 text-4xl font-bold leading-tight sm:text-5xl">자산과 계약 현황</h1><p className="mt-6 text-lg text-navy-200">제목, 본문, 버튼과 여백을 확인하는 디자인 예시입니다. 실제 서비스 조건이나 자금 지급을 안내하는 페이지가 아닙니다.</p><div className="mt-8"><ButtonLink href="#sample-content" size="lg">예시 내용 보기</ButtonLink></div></div></section><section id="sample-content" className="ph-section mx-auto max-w-5xl px-6"><h2 className="text-3xl font-bold">정보의 순서와 표현</h2><div className="ph-feature-list mt-10"><div><h3 className="text-xl font-semibold">가상 자산 목록</h3><p className="mt-3 text-navy-600">긴 한글, 숫자와 날짜를 읽기 쉽게 배치합니다.</p></div><div><h3 className="text-xl font-semibold">가상 문서 상태</h3><p className="mt-3 text-navy-600">대기, 확인 필요, 오류를 텍스트로 구분합니다.</p></div></div></section></main><footer className="border-t border-navy-100 px-6 py-8 text-sm text-navy-500">디자인 검토용 가상 연락처: preview@example.com</footer></>;}
function App(){const query=new URLSearchParams(window.location.search);const page=query.get('view')==='public'?'public':'admin';const width=query.get('viewport');if(width==='390'||width==='768'){const q=new URLSearchParams({view:page,frame:'1'});return <main className="min-h-screen bg-navy-50 p-5"><h1 className="text-xl font-semibold">{width}px 반응형 검토</h1><p className="my-3 text-sm">동일한 UI를 {width}px iframe viewport로 표시합니다. 실기기 터치는 별도 검수 대상입니다.</p><a className="ph-button ph-button--secondary mb-4" href={'/?view='+page}>전체 화면으로 돌아가기</a><iframe title={`${width}px 풍현 디자인 검토`} src={'/?'+q} width={width} height="950" style={{display:'block',border:'1px solid #525c6a',maxWidth:'100%',background:'white'}}/></main>;}return <><div className="preview-banner"><strong>풍현 디자인 검토 v1.1</strong><p>가상자료 전용 · 운영 데이터/업무 로직 없음</p><nav aria-label="검토 화면"><a href="/?view=admin" aria-current={page==='admin'?'page':undefined}>관리자형 예시</a><a href="/?view=public" aria-current={page==='public'?'page':undefined}>공개형 예시</a>{query.get('frame')!=='1'&&<><a href={'/?view='+page+'&viewport=390'}>390px</a><a href={'/?view='+page+'&viewport=768'}>768px</a></>}</nav></div>{page==='public'?<PublicSample/>:<Gallery/>}</>;}
createRoot(document.getElementById('root')!).render(<App/>);
